sudo: required
services:
  - docker

before_install:
  - docker build -t th-lamb/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run th-lamb/udemy-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  redion: "us-east-1"
  app: "udemy-docker-react"
  env: "Udemydockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-121986536897"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
