sudo: required
services:
  - docker

before_install:
  - docker build -t th-lamb/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run th-lamb/udemy-docker-react npm run test -- --coverage
